version: "3"

volumes:
  db:


services:
  mysql:
    image: mysql:5.7.20
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: thisismypassword

  app:
    build:
      context: .
      # specified so that you can run `docker-compose push`
    image: your.registry.url
    restart: always
    ports:
      - 8089:5000
